# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "rainbow", "~> 3.0"

gem 'artii', '~> 2.1', '>= 2.1.2'

gem 'tty-prompt', '~> 0.23.1'

gem 'colorize', '~> 0.8.1'



