# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "asciiart", "~> 0.0.7"

gem "rainbow", "~> 3.0"

gem "word_wrap", "~> 1.0"

gem 'json', '~> 2.5', '>= 2.5.1'



